"""Orders module - plan step P-044.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260924-015812.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
from _lib.flows import auth_flow
import re


def _order(page: Page, base_url, pid):
    page.goto(f"{base_url}/catalog.html")
    page.click(f"[data-test='add-{pid}']")
    page.goto(f"{base_url}/checkout.html")
    page.fill("[data-test='full-name']", "Ana Tan")
    page.fill("[data-test='postcode']", "123456")
    page.click("[data-test='place-order']")
    expect(page).to_have_url(re.compile(r"/confirmation\.html$"))


@pytest.mark.functional
def test_order_history_newest_first(page: Page, base_url, credentials):
    """TC100 [key:e150dc95b449] [plan:P-044]
    provenance: confirmed against REQ-ORDER-02. Desk Lamp $42.50 + $3.40 + $6.50; Canvas Tote $18.00 + $1.44 + $6.50."""
    auth_flow.login(page, base_url, credentials["standard"])
    _order(page, base_url, "p2")
    _order(page, base_url, "p1")
    page.goto(f"{base_url}/orders.html")
    rows = page.locator("[data-test='order-row']")
    expect(rows).to_have_count(2)
    expect(rows.locator("[data-test='order-no']")).to_have_text(["SO-1002", "SO-1001"])
    expect(rows.locator("[data-test='order-items']")).to_have_text(["1", "1"])
    expect(rows.locator("[data-test='order-total']")).to_have_text(["$25.94", "$52.40"])
    expect(rows.locator("[data-test='order-status']")).to_have_text(["Placed", "Placed"])
