"""Login module - plan steps P-001 to P-004.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260923-184017.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
import re
from _lib.flows import auth_flow


@pytest.mark.smoke
@pytest.mark.functional
def test_catalog_requires_login(page: Page, base_url):
    """TC004 [key:5631d3e93ff7] [plan:P-004] provenance: observed."""
    page.goto(f"{base_url}/catalog.html")
    expect(page).to_have_url(re.compile(r"index\.html\?error=login-required$"))
    expect(page.locator("[data-test='error']")).to_have_text("You must log in to view that page.")


@pytest.mark.functional
def test_locked_account_is_refused(page: Page, base_url, credentials):
    """TC003 [key:be43037697a1] [plan:P-003]
    provenance: confirmed against REQ-LOCK."""
    auth_flow.login(page, base_url, credentials["locked"], expect_success=False)
    expect(page.locator("[data-test='error']")).to_have_text("This account is locked. Contact support.")


@pytest.mark.smoke
@pytest.mark.functional
def test_login_lands_on_catalog(page: Page, base_url, credentials):
    """TC001 [key:ab680631d87c] [plan:P-001] provenance: observed.
    Valid credentials land on the catalog."""
    auth_flow.login(page, base_url, credentials["standard"])
    expect(page).to_have_url(re.compile(r"/catalog\.html$"))
    expect(page.locator("[data-test='product-list']")).to_be_visible()


@pytest.mark.functional
def test_login_wrong_password_shows_mismatch_error(page: Page, base_url):
    """TC002 [key:0c1367759bd5] [plan:P-002] provenance: observed."""
    auth_flow.login(page, base_url, {"username": "standard_user", "password": "not-the-password"},
                    expect_success=False)
    expect(page.locator("[data-test='error']")).to_have_text("Username and password do not match.")
    expect(page).to_have_url(re.compile(r"/index\.html$|/$"))


@pytest.mark.functional
def test_locked_account_cannot_reach_catalog(page: Page, base_url, credentials):
    """TC005 [key:fe00ed535b25] [plan:P-018]
    provenance: confirmed against REQ-LOCK. "Cannot log in": stays on the login page, catalog refused."""
    auth_flow.login(page, base_url, credentials["locked"], expect_success=False)
    expect(page.locator("[data-test='error']")).to_be_visible()  # the attempt has been processed
    expect(page).to_have_url(re.compile(r"/index\.html$|/$"))
    page.goto(f"{base_url}/catalog.html")
    expect(page).to_have_url(re.compile(r"index\.html\?error=login-required$"))


@pytest.mark.functional
def test_customer_cannot_use_admin_page(page: Page, base_url, credentials):
    """TC006 [key:5830a8821b07] [plan:P-045]
    provenance: confirmed against REQ-AUTH-02."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.goto(f"{base_url}/admin.html")
    expect(page.locator("[data-test='admin-denied']")).to_have_text("Admins only.")
    expect(page.locator("input[data-test^='admin-stock-p']")).to_have_count(0)
    expect(page.locator("[data-test='nav-admin']")).to_be_hidden()
