"""Stock module - plan steps P-032 to P-034.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260924-015812.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
from _lib.flows import auth_flow


@pytest.mark.functional
def test_admin_zero_stock_blocks_adding(page: Page, base_url, credentials):
    """TC071 [key:0e0cb2ad4f6a] [plan:P-033]
    provenance: confirmed against REQ-ADMIN-01. Also REQ-STOCK-01; depends on the admin page working."""
    auth_flow.login(page, base_url, credentials["admin"])
    page.goto(f"{base_url}/admin.html")
    page.fill("[data-test='admin-stock-p2']", "0")
    page.press("[data-test='admin-stock-p2']", "Tab")
    expect(page.locator("[data-test='admin-saved']")).to_be_visible()
    page.click("[data-test='logout']")
    auth_flow.login(page, base_url, credentials["standard"])
    expect(page.locator("[data-test='add-p2']")).to_be_disabled()
    expect(page.locator("[data-test='add-p2']")).to_have_text("Out of stock")


@pytest.mark.functional
def test_low_stock_shows_only_n_left(page: Page, base_url, credentials):
    """TC072 [key:6f4f540cf5b4] [plan:P-034]
    provenance: confirmed against REQ-STOCK-01. Linen Apron has 2 left."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.goto(f"{base_url}/product.html?id=p12")
    expect(page.locator("[data-test='pdp-stock']")).to_have_text("Only 2 left")


@pytest.mark.functional
def test_out_of_stock_product_cannot_be_added(page: Page, base_url, credentials):
    """TC070 [key:84f462a0fa33] [plan:P-032]
    provenance: confirmed against REQ-STOCK-01. Wall Clock has 0 in stock."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.goto(f"{base_url}/products.html")
    page.fill("[data-test='search-input']", "Wall Clock")
    expect(page.locator("[data-test='add-p16']")).to_be_disabled()
    expect(page.locator("[data-test='add-p16']")).to_have_text("Out of stock")
    page.goto(f"{base_url}/product.html?id=p16")
    expect(page.locator("[data-test='add-to-cart']")).to_be_disabled()
