"""Review module - plan steps P-028 to P-030.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260924-015812.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
from _lib.flows import auth_flow


ITEM = "[data-test='review-item']"


ERROR = "[data-test='review-error']"


def _submit(page: Page, rating: str, text: str):
    if rating:
        page.select_option("[data-test='review-rating']", rating)
    page.fill("[data-test='review-text']", text)
    page.click("[data-test='review-submit']")


def _review_page(page: Page, base_url, credentials, pid="p1"):
    auth_flow.login(page, base_url, credentials["standard"])
    page.goto(f"{base_url}/product.html?id={pid}")


@pytest.mark.functional
def test_one_review_per_customer(page: Page, base_url, credentials):
    """TC062 [key:2148b58f2c67] [plan:P-030]
    provenance: confirmed against REQ-REVIEW-02."""
    _review_page(page, base_url, credentials)
    _submit(page, "5", "Carried it every day for a month.")
    expect(page.locator(ITEM)).to_have_count(1)
    _submit(page, "3", "Changed my mind about the colour.")
    expect(page.locator(ERROR)).to_have_text("You have already reviewed this product.")
    expect(page.locator(ITEM)).to_have_count(1)


@pytest.mark.extended
@pytest.mark.functional
def test_review_text_length_limits(page: Page, base_url, credentials):
    """TC061 [key:92f65d87aec3] [plan:P-029]
    provenance: confirmed against REQ-REVIEW-01. 9 characters rejected, 10 accepted (the boundary)."""
    _review_page(page, base_url, credentials)
    _submit(page, "4", "Nice bag.")  # 9 characters
    expect(page.locator(ERROR)).to_have_text("Review text must be 10 to 500 characters.")
    expect(page.locator(ITEM)).to_have_count(0)
    _submit(page, "4", "Great tote")  # 10 characters
    expect(page.locator(ERROR)).to_be_hidden()
    expect(page.locator(ITEM)).to_have_count(1)


@pytest.mark.functional
def test_review_without_rating_is_rejected(page: Page, base_url, credentials):
    """TC060 [key:ddf322dac29b] [plan:P-028]
    provenance: confirmed against REQ-REVIEW-01."""
    _review_page(page, base_url, credentials)
    _submit(page, "", "Sturdy bag, the strap is comfortable.")
    expect(page.locator(ERROR)).to_have_text("Choose a rating from 1 to 5 stars.")
    expect(page.locator(ITEM)).to_have_count(0)
