"""Product detail module - plan step P-027.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260924-015812.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
from _lib.flows import auth_flow


RATING = "[data-test='pdp-rating']"


@pytest.mark.functional
def test_average_rating_to_one_decimal(page: Page, base_url, credentials):
    """TC050 [key:6a48c0930711] [plan:P-027]
    provenance: confirmed against REQ-PDP-01. Wool Throw ratings 5, 5, 4: mean 4.67 shows as 4.7."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.goto(f"{base_url}/product.html?id=p5")
    expect(page.locator(RATING)).to_have_text("4.7 out of 5 (3 reviews)")
    page.goto(f"{base_url}/product.html?id=p1")
    expect(page.locator(RATING)).to_have_text("No reviews yet")
