"""Shipping module - plan steps P-041 to P-043.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260924-015812.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
from _lib.flows import auth_flow


SHIPPING = "[data-test='shipping']"


def _checkout_with(page: Page, base_url, creds, *ids):
    auth_flow.login(page, base_url, creds)
    for pid in ids:
        page.click(f"[data-test='add-{pid}']")
    page.goto(f"{base_url}/checkout.html")


@pytest.mark.functional
def test_free_shipping_threshold_after_discounts(page: Page, base_url, credentials):
    """TC092 [key:0341198bacfe] [plan:P-043]
    provenance: confirmed against REQ-SHIP-04. $76.49 ships free; SAVE10 takes it to $68.84, which does not."""
    _checkout_with(page, base_url, credentials["standard"], "p2", "p6", "p3")
    expect(page.locator("[data-test='subtotal']")).to_have_text("$76.49")
    expect(page.locator(SHIPPING)).to_have_text("Free")
    page.fill("[data-test='promo-input']", "SAVE10")
    page.click("[data-test='promo-apply']")
    expect(page.locator("[data-test='discount']")).to_have_text("-$7.65")
    expect(page.locator(SHIPPING)).to_have_text("$6.50")


@pytest.mark.functional
def test_regional_surcharge_is_added(page: Page, base_url, credentials):
    """TC090 [key:0408ea76ac0d] [plan:P-041]
    provenance: confirmed against REQ-SHIP-02. $6.50 + $5.00 below $75; free base + $5.00 above."""
    _checkout_with(page, base_url, credentials["standard"], "p2")
    page.select_option("[data-test='region']", "Regional")
    expect(page.locator(SHIPPING)).to_have_text("$11.50")
    page.goto(f"{base_url}/catalog.html")
    page.click("[data-test='add-p5']")  # $162.50
    page.goto(f"{base_url}/checkout.html")
    page.select_option("[data-test='region']", "Regional")
    expect(page.locator(SHIPPING)).to_have_text("$5.00")


@pytest.mark.functional
def test_remote_shipping_is_always_fourteen(page: Page, base_url, credentials):
    """TC091 [key:052a340d8f19] [plan:P-042]
    provenance: confirmed against REQ-SHIP-03. Never free: not over $75, not with FREESHIP."""
    _checkout_with(page, base_url, credentials["standard"], "p2", "p5")
    page.select_option("[data-test='region']", "Remote")
    expect(page.locator(SHIPPING)).to_have_text("$14.00")
    page.goto(f"{base_url}/catalog.html")
    page.click("[data-test='remove-p5']")  # $42.50
    page.goto(f"{base_url}/checkout.html")
    page.fill("[data-test='promo-input']", "FREESHIP")
    page.click("[data-test='promo-apply']")
    page.select_option("[data-test='region']", "Remote")
    expect(page.locator(SHIPPING)).to_have_text("$14.00")
