"""Promo module - plan steps P-035 to P-039.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260924-015812.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
from _lib.flows import auth_flow


DISCOUNT = "[data-test='discount']"


NOT_VALID = "This code is not valid."


PROMO_ERROR = "[data-test='promo-error']"


def _checkout_with(page: Page, base_url, creds, *ids):
    auth_flow.login(page, base_url, creds)
    for pid in ids:
        page.click(f"[data-test='add-{pid}']")
    page.goto(f"{base_url}/checkout.html")


def _apply(page: Page, code: str):
    page.fill("[data-test='promo-input']", code)
    page.click("[data-test='promo-apply']")


@pytest.mark.functional
def test_code_disabled_by_admin_is_not_valid(page: Page, base_url, credentials):
    """TC084 [key:5551a0c37f42] [plan:P-039]
    provenance: confirmed against REQ-ADMIN-02. Also REQ-PROMO-01; depends on the admin page working."""
    auth_flow.login(page, base_url, credentials["admin"])
    page.goto(f"{base_url}/admin.html")
    page.uncheck("[data-test='admin-promo-SAVE10']")
    expect(page.locator("[data-test='admin-saved']")).to_be_visible()
    page.click("[data-test='logout']")
    _checkout_with(page, base_url, credentials["standard"], "p2")
    _apply(page, "SAVE10")
    expect(page.locator(PROMO_ERROR)).to_have_text(NOT_VALID)
    expect(page.locator(DISCOUNT)).to_have_text("$0.00")


@pytest.mark.functional
def test_freeship_combines_with_a_discount_code(page: Page, base_url, credentials):
    """TC081 [key:511c48813a1e] [plan:P-036]
    provenance: confirmed against REQ-PROMO-02. FREESHIP is not a discount code."""
    _checkout_with(page, base_url, credentials["standard"], "p2")
    _apply(page, "SAVE10")
    _apply(page, "FREESHIP")
    expect(page.locator(PROMO_ERROR)).to_be_hidden()
    expect(page.locator(DISCOUNT)).to_have_text("-$4.25")
    expect(page.locator("[data-test='shipping']")).to_have_text("Free")


@pytest.mark.functional
def test_only_one_discount_code_per_order(page: Page, base_url, credentials):
    """TC080 [key:f0e5a55c70bf] [plan:P-035]
    provenance: confirmed against REQ-PROMO-02. The struck rule (two codes stack) must not apply."""
    _checkout_with(page, base_url, credentials["standard"], "p5")
    _apply(page, "SAVE10")
    _apply(page, "WELCOME5")
    expect(page.locator(PROMO_ERROR)).to_have_text("Only one discount code can be used per order.")
    expect(page.locator(DISCOUNT)).to_have_text("-$12.00")
    expect(page.locator("[data-test='promo-applied']")).to_have_text("SAVE10")


@pytest.mark.functional
def test_unknown_code_is_not_valid(page: Page, base_url, credentials):
    """TC083 [key:702de2ec6205] [plan:P-038]
    provenance: confirmed against REQ-PROMO-01."""
    _checkout_with(page, base_url, credentials["standard"], "p2")
    _apply(page, "SAVE20")
    expect(page.locator(PROMO_ERROR)).to_have_text(NOT_VALID)
    expect(page.locator(DISCOUNT)).to_have_text("$0.00")


@pytest.mark.functional
def test_welcome5_needs_thirty_dollars(page: Page, base_url, credentials):
    """TC082 [key:a16f8c54cd7a] [plan:P-037]
    provenance: confirmed against REQ-PROMO-03. Confluence $30 wins over the $25 in story SHOP-18."""
    _checkout_with(page, base_url, credentials["standard"], "p1", "p3")  # $27.99
    _apply(page, "WELCOME5")
    expect(page.locator(PROMO_ERROR)).to_have_text("WELCOME5 needs a subtotal of $30 or more.")
    expect(page.locator(DISCOUNT)).to_have_text("$0.00")
    page.goto(f"{base_url}/cart.html")
    page.click("[data-test='cart-remove-p3']")
    page.goto(f"{base_url}/products.html")
    page.fill("[data-test='search-input']", "Scented Candle")
    page.click("[data-test='add-p15']")  # $18.00 + $12.00 = $30.00
    page.goto(f"{base_url}/checkout.html")
    expect(page.locator("[data-test='subtotal']")).to_have_text("$30.00")
    _apply(page, "WELCOME5")
    expect(page.locator(DISCOUNT)).to_have_text("-$5.00")
