"""Catalog module - plan steps P-005 to P-007.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260923-184017.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from _lib.flows import auth_flow
from playwright.sync_api import Page, expect

PRICES_LOW_TO_HIGH = ["$7.50", "$9.99", "$18.00", "$24.00", "$42.50", "$120.00"]


@pytest.mark.functional
def test_price_sort_is_numeric(page: Page, base_url, credentials):
    """TC010 [key:2ba0dcbf93dd] [plan:P-005]
    provenance: confirmed against REQ-SORT."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.select_option("[data-test='sort']", "price-asc")
    expect(page.locator("[data-test='product-price']")).to_have_text(PRICES_LOW_TO_HIGH)


NAMES_A_TO_Z = ["Canvas Tote", "Ceramic Planter", "Desk Lamp", "Espresso Cups", "Field Notebook", "Wool Throw"]

PRICES_HIGH_TO_LOW = ["$120.00", "$42.50", "$24.00", "$18.00", "$9.99", "$7.50"]


@pytest.mark.functional
def test_name_sort_a_to_z(page: Page, base_url, credentials):
    """TC011 [key:00fd74de6758] [plan:P-020]
    provenance: confirmed against REQ-SORT."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.select_option("[data-test='sort']", "name-asc")
    expect(page.locator("[data-test='product-name']")).to_have_text(NAMES_A_TO_Z)


@pytest.mark.functional
def test_name_sort_z_to_a(page: Page, base_url, credentials):
    """TC012 [key:67e0f5d84c4d] [plan:P-021]
    provenance: confirmed against REQ-SORT."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.select_option("[data-test='sort']", "name-desc")
    expect(page.locator("[data-test='product-name']")).to_have_text(list(reversed(NAMES_A_TO_Z)))


@pytest.mark.functional
def test_price_sort_high_to_low(page: Page, base_url, credentials):
    """TC013 [key:03318ba0cd92] [plan:P-022]
    provenance: confirmed against REQ-SORT."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.select_option("[data-test='sort']", "price-desc")
    expect(page.locator("[data-test='product-price']")).to_have_text(PRICES_HIGH_TO_LOW)
