"""Search module (All products) - plan steps P-023 to P-026.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260924-015812.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
from _lib.flows import auth_flow


ALL_PRODUCTS = 18


NAME = "[data-test='product-name']"


KITCHEN_IN_STOCK = ["Cast Iron Skillet", "Chef's Knife", "Cutting Board", "Espresso Cups",
                    "Linen Apron", "Olive Oil Cruet", "Salad Bowl", "Tea Kettle"]


def _all_products(page: Page, base_url, credentials):
    auth_flow.login(page, base_url, credentials["standard"])
    page.goto(f"{base_url}/products.html")


@pytest.mark.functional
def test_every_product_appears_once_across_pages(page: Page, base_url, credentials):
    """TC043 [key:7f5e0fb5f131] [plan:P-026]
    provenance: confirmed against REQ-SEARCH-03. 18 products, 8 per page = 3 pages, each exactly once."""
    _all_products(page, base_url, credentials)
    expect(page.locator("[data-test='page-indicator']")).to_have_text("Page 1 of 3")
    seen = []
    for page_no in (1, 2, 3):
        expect(page.locator("[data-test='page-indicator']")).to_have_text(f"Page {page_no} of 3")
        seen += page.locator(NAME).all_inner_texts()
        if page_no < 3:
            page.click("[data-test='page-next']")
    expect(page.locator("[data-test='page-next']")).to_be_hidden()
    assert len(seen) == ALL_PRODUCTS, f"{len(seen)} cards shown for {ALL_PRODUCTS} products: {seen}"
    assert len(set(seen)) == ALL_PRODUCTS


@pytest.mark.functional
def test_kitchen_in_stock_fits_one_page(page: Page, base_url, credentials):
    """TC042 [key:93f7fb02eedb] [plan:P-025]
    provenance: confirmed against REQ-SEARCH-02. Filters combine (AND); exactly 8 = one page."""
    _all_products(page, base_url, credentials)
    page.select_option("[data-test='filter-category']", "Kitchen")
    page.check("[data-test='filter-in-stock']")
    expect(page.locator(NAME)).to_have_text(KITCHEN_IN_STOCK)
    expect(page.locator("[data-test='page-indicator']")).to_have_text("Page 1 of 1")
    expect(page.locator("[data-test='page-next']")).to_be_hidden()


@pytest.mark.smoke
@pytest.mark.functional
def test_search_ignores_case(page: Page, base_url, credentials):
    """TC040 [key:107f484cbc64] [plan:P-023]
    provenance: confirmed against REQ-SEARCH-01. Lower and upper case both find Desk Lamp."""
    _all_products(page, base_url, credentials)
    for query in ("lamp", "LAMP"):
        page.fill("[data-test='search-input']", query)
        expect(page.locator(NAME)).to_have_text(["Desk Lamp"])


@pytest.mark.functional
def test_search_without_matches_shows_empty_message(page: Page, base_url, credentials):
    """TC041 [key:5377462e0088] [plan:P-024]
    provenance: confirmed against REQ-SEARCH-01."""
    _all_products(page, base_url, credentials)
    page.fill("[data-test='search-input']", "zebra")
    expect(page.locator("[data-test='product']")).to_have_count(0)
    expect(page.locator("[data-test='empty-results']")).to_have_text("No products match.")
    expect(page.locator("[data-test='pager']")).to_be_hidden()
