"""Cart module - plan steps P-008 to P-010.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260923-184017.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from _lib.flows import auth_flow
from playwright.sync_api import Page, expect

BADGE = "[data-test='cart-badge']"


@pytest.mark.functional
def test_badge_decrements_on_remove(page: Page, base_url, credentials):
    """TC021 [key:864b1923b6e7] [plan:P-009]
    provenance: confirmed against REQ-CART."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.click("[data-test='add-p2']")
    page.click("[data-test='add-p5']")
    expect(page.locator(BADGE)).to_have_text("2")
    page.click("[data-test='remove-p5']")
    expect(page.locator(BADGE)).to_have_text("1")


@pytest.mark.functional
def test_badge_hidden_when_cart_empty(page: Page, base_url, credentials):
    """TC022 [key:c2532dfeabcb] [plan:P-010]
    provenance: confirmed against REQ-CART."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.click("[data-test='add-p3']")
    expect(page.locator(BADGE)).to_be_visible()
    page.click("[data-test='remove-p3']")
    expect(page.locator(BADGE)).to_be_hidden()


@pytest.mark.smoke
@pytest.mark.functional
def test_badge_increments_on_add(page: Page, base_url, credentials):
    """TC020 [key:f0f7368d9d61] [plan:P-008]
    provenance: confirmed against REQ-CART."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.click("[data-test='add-p2']")
    expect(page.locator(BADGE)).to_have_text("1")
    page.click("[data-test='add-p5']")
    expect(page.locator(BADGE)).to_have_text("2")


@pytest.mark.functional
def test_badge_counts_quantities(page: Page, base_url, credentials):
    """TC023 [key:c03325b40533] [plan:P-031]
    provenance: confirmed against REQ-CART-02. Also REQ-CART: the badge is the sum of the quantities."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.goto(f"{base_url}/product.html?id=p2")
    page.select_option("[data-test='qty']", "3")
    page.click("[data-test='add-to-cart']")
    expect(page.locator(BADGE)).to_have_text("3")
    page.goto(f"{base_url}/cart.html")
    page.select_option("[data-test='cart-qty-p2']", "1")
    expect(page.locator(BADGE)).to_have_text("1")
