"""Checkout module - plan steps P-011 to P-014.

Generated by the generator role (Rule 22) from consolidated/gene2-demo-shop/specs/plan-20260923-184017.md.
Every [key:...] comes from tools/suite_audit.py's hash (gene2 key), never typed by hand."""
import pytest
from playwright.sync_api import Page, expect
import re
from _lib.flows import auth_flow

TAX_RATE = 0.08

DESK_LAMP, WOOL_THROW = 42.50, 120.00

def _checkout_with(page: Page, base_url, credentials, *ids):
    auth_flow.login(page, base_url, credentials["standard"])
    for pid in ids:
        page.click(f"[data-test='add-{pid}']")
    page.goto(f"{base_url}/checkout.html")

def _money(x: float) -> str:
    return f"${x:.2f}"


@pytest.mark.bug
def test_double_submit_records_one_order(page: Page, base_url, credentials):
    """TC033 [key:a00acfa89b6d] [plan:P-014]
    provenance: confirmed against REQ-ORDER. Bug reproduction: fails until submit is idempotent."""
    _checkout_with(page, base_url, credentials, "p2")
    page.fill("[data-test='full-name']", "Ana Tan")
    page.fill("[data-test='postcode']", "123456")
    page.dblclick("[data-test='place-order']")
    expect(page).to_have_url(re.compile(r"/confirmation\.html$"))
    expect(page.locator("[data-test='order-count']")).to_have_text("1")


@pytest.mark.bug
def test_postcode_is_required(page: Page, base_url, credentials):
    """TC032 [key:85f73fc01d9a] [plan:P-013]
    provenance: confirmed against REQ-POSTCODE. Bug reproduction: fails until the app enforces it."""
    _checkout_with(page, base_url, credentials, "p2")
    page.fill("[data-test='full-name']", "Ana Tan")
    page.click("[data-test='place-order']")
    expect(page.locator("[data-test='checkout-error']")).to_be_visible(timeout=3_000)
    expect(page).to_have_url(re.compile(r"/checkout\.html$"))


@pytest.mark.smoke
@pytest.mark.functional
def test_tax_is_eight_percent_of_subtotal(page: Page, base_url, credentials):
    """TC030 [key:68bc7fc78a9e] [plan:P-011]
    provenance: confirmed against REQ-TAX."""
    _checkout_with(page, base_url, credentials, "p2")
    expected = _money(round(DESK_LAMP * TAX_RATE, 2))
    expect(page.locator("[data-test='tax']")).to_have_text(expected)


def _change_cart(page: Page, base_url, add=(), remove=()):
    page.goto(f"{base_url}/catalog.html")
    for pid in remove:
        page.click(f"[data-test='remove-{pid}']")
    for pid in add:
        page.click(f"[data-test='add-{pid}']")
    page.goto(f"{base_url}/checkout.html")


@pytest.mark.functional
def test_orders_of_75_or_less_pay_flat_shipping(page: Page, base_url, credentials):
    """TC036 [key:f4024c2a8d19] [plan:P-017]
    provenance: confirmed against REQ-SHIP. $6.50 at $42.50 and at $74.00, the closest total below $75."""
    _checkout_with(page, base_url, credentials, "p2")
    expect(page.locator("[data-test='subtotal']")).to_have_text("$42.50")
    expect(page.locator("[data-test='shipping']")).to_have_text("$6.50")
    _change_cart(page, base_url, add=("p6", "p4"))
    expect(page.locator("[data-test='subtotal']")).to_have_text("$74.00")
    expect(page.locator("[data-test='shipping']")).to_have_text("$6.50")


@pytest.mark.functional
def test_orders_over_75_ship_free(page: Page, base_url, credentials):
    """TC035 [key:dded027fe67d] [plan:P-016]
    provenance: confirmed against REQ-SHIP. Free at $162.50 and at $76.49, the closest total above $75."""
    _checkout_with(page, base_url, credentials, "p2", "p5")
    expect(page.locator("[data-test='subtotal']")).to_have_text("$162.50")
    expect(page.locator("[data-test='shipping']")).to_have_text("Free")
    _change_cart(page, base_url, add=("p6", "p3"), remove=("p5",))
    expect(page.locator("[data-test='subtotal']")).to_have_text("$76.49")
    expect(page.locator("[data-test='shipping']")).to_have_text("Free")


@pytest.mark.functional
def test_tax_rounds_to_nearest_cent(page: Page, base_url, credentials):
    """TC034 [key:812bb77b3ca9] [plan:P-015]
    provenance: confirmed against REQ-TAX. 9.99 x 0.08 = 0.7992 rounds to $0.80 (truncation gives $0.79)."""
    _checkout_with(page, base_url, credentials, "p3")
    expect(page.locator("[data-test='subtotal']")).to_have_text("$9.99")
    expect(page.locator("[data-test='tax']")).to_have_text("$0.80")


@pytest.mark.functional
def test_tax_on_discounted_subtotal(page: Page, base_url, credentials):
    """TC037 [key:ddd9593ffc9f] [plan:P-040]
    provenance: confirmed against REQ-TAX-02. $42.50 - $5.00 = $37.50; 8% = $3.00; + $6.50 = $47.00."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.click("[data-test='add-p2']")
    page.goto(f"{base_url}/checkout.html")
    page.fill("[data-test='promo-input']", "WELCOME5")
    page.click("[data-test='promo-apply']")
    expect(page.locator("[data-test='discount']")).to_have_text("-$5.00")
    expect(page.locator("[data-test='tax']")).to_have_text("$3.00")
    expect(page.locator("[data-test='total']")).to_have_text("$47.00")


@pytest.mark.smoke
def test_place_order_shows_confirmation_and_empties_cart(page: Page, base_url, credentials):
    """TC038 [key:3efe638be7a0] [plan:P-047]
    provenance: confirmed against REQ-CHK-02. Also REQ-CHK-01 (first order SO-1001), REQ-PAY-01 (no payment step)."""
    auth_flow.login(page, base_url, credentials["standard"])
    page.click("[data-test='add-p2']")
    page.goto(f"{base_url}/checkout.html")
    page.fill("[data-test='full-name']", "Ana Tan")
    page.fill("[data-test='postcode']", "123456")
    page.click("[data-test='place-order']")
    expect(page).to_have_url(re.compile(r"/confirmation\.html$"))
    expect(page.locator("[data-test='confirmation-title']")).to_have_text("Thank you, your order is placed.")
    expect(page.locator("[data-test='order-number']")).to_have_text("SO-1001")
    page.goto(f"{base_url}/cart.html")
    badge = page.locator("[data-test='cart-badge']")
    expect(badge).to_have_count(1)
    expect(badge).to_be_hidden()
    expect(page.locator("[data-test='cart-empty']")).to_be_visible()


CHECKOUT_URL = re.compile(r"/checkout\.html$")


def _cart_with_lamp(page: Page, base_url, creds):
    auth_flow.login(page, base_url, creds)
    page.goto(f"{base_url}/catalog.html")
    page.click("[data-test='add-p2']")


def _fresh_checkout(page: Page, base_url):
    """checkout-error is never cleared on resubmit, so each case starts on a freshly loaded form."""
    page.goto(f"{base_url}/checkout.html")
    error = page.locator("[data-test='checkout-error']")
    expect(error).to_be_hidden()
    return error


@pytest.mark.functional
def test_admin_checkout_address_is_saved_address(page: Page, base_url, credentials):
    """TC132 [key:a0d04d9bed00] [plan:P-053]
    provenance: confirmed against REQ-ROLE-01."""
    _cart_with_lamp(page, base_url, credentials["admin"])
    page.goto(f"{base_url}/checkout.html")
    expect(page.locator("[data-test='address']")).to_have_value("1 Depot Lane")


@pytest.mark.functional
def test_empty_address_is_rejected(page: Page, base_url, credentials):
    """TC039 [key:52385492512f] [plan:P-051]
    provenance: confirmed against REQ-ADDR-01 (ERR-15), REQ-MSG-03 (no order recorded)."""
    _cart_with_lamp(page, base_url, credentials["standard"])
    error = _fresh_checkout(page, base_url)
    page.fill("[data-test='full-name']", "Ana Tan")
    page.fill("[data-test='postcode']", "123456")
    page.fill("[data-test='address']", "")
    page.click("[data-test='place-order']")
    expect(error).to_have_text("Address is required.")
    expect(page).to_have_url(CHECKOUT_URL)
    page.goto(f"{base_url}/orders.html")
    expect(page.locator("[data-test='orders-empty']")).to_have_text("No orders yet.")


@pytest.mark.functional
def test_full_name_length_is_enforced(page: Page, base_url, credentials):
    """TC031 [key:5191642001a8] [plan:P-050]
    provenance: confirmed against REQ-ADDR-01 (ERR-13), REQ-MSG-01. 1 and 61 characters."""
    _cart_with_lamp(page, base_url, credentials["standard"])
    for name in ("A", "A" * 61):
        error = _fresh_checkout(page, base_url)
        page.fill("[data-test='full-name']", name)
        page.fill("[data-test='postcode']", "123456")
        page.click("[data-test='place-order']")
        expect(error).to_have_text("Full name must be 2 to 60 characters.")
        expect(page).to_have_url(CHECKOUT_URL)
        expect(page.locator("[data-test='full-name']")).to_have_value(name)


@pytest.mark.bug
def test_postcode_must_be_six_digits(page: Page, base_url, credentials):
    """TC131 [key:e326568c8c46] [plan:P-052]
    provenance: confirmed against REQ-POSTCODE (ERR-14). Bug reproduction: fails until the app
    rejects a postcode that is not 6 digits."""
    _cart_with_lamp(page, base_url, credentials["standard"])
    for postcode in ("12345", "1234567", "12a456"):
        error = _fresh_checkout(page, base_url)
        page.fill("[data-test='full-name']", "Ana Tan")
        page.fill("[data-test='postcode']", postcode)
        page.click("[data-test='place-order']")
        expect(error).to_have_text("A 6-digit postcode is required.", timeout=3_000)
        expect(page).to_have_url(CHECKOUT_URL)
